### ISSUE TITLE
error to add list to page

### ISSUE THREAD

**Issue by prefair** [DrivenNetwork/pagekit-listings#9] opened 2017-01-05 15:19 UTC
if i place "(listings){"id":"2"}" in my page then i get only this on my page as plain text:
script('driven.list', 'driven/listings:js/list.js', ['vue']) ?> style('driven.uikit', 'driven/listings:/assets/css/uikit.min.css') ?>

**Comment by luisreyes** [comment] 2017-01-05 15:47
This could be caused by [Short Tags].
I will fix this on the next release. 

In the meantime: Make sure your PHP Settings are ON for short_tags.
http://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags

**Comment by luisreyes** [comment] 2017-01-05 16:27
Actually... all short tags where remove already by @tobbexiv. In PR https://github.com/DrivenNetwork/pagekit-listings/commit/007066e5d4b2b2287efc946aacd01777f5f8842c
I need more details to help you.

**PHP Version: ??**
**Pagekit Version: ??**
**Listings Version: ??**

Where exactly are you placing `(listings){"id":"2"}`?
Do you have any error logs?

**Comment by prefair** [comment] 2017-01-09 11:48
PHP Version: 5.6.29-0+deb8u1
Pagekit Version: 1.0.10
Listings Version: 1.0.3

I fix it with short tags.

**Comment by luisreyes** [comment] 2017-01-09 12:14
Glad to hear it's working. Closing the issue.

**Closed by luisreyes** 2017-01-09 12:14 UTC
